import type { Story } from "./types";

export const seedStories: Story[] = [
  {
    id: "s01",
    lat: 55.8,
    lng: 37.6,
    lang: "ru",
    text: "Потерял работу после 8 лет. Семья не понимает. Чувствую себя невидимкой.",
    feeling: null,
    coped: "Начал гулять каждое утро. Мелочь, но помогает.",
  },
  {
    id: "s02",
    lat: 40.7,
    lng: -74.0,
    lang: "en",
    text: "Laid off. 300 applications. Nothing. Savings running out.",
    feeling: null,
    coped: "Found a free community at the library. Just being around people helps.",
  },
  {
    id: "s03",
    lat: 51.5,
    lng: -0.1,
    lang: "en",
    text: "Moved to a new country alone. No friends, no family nearby. The loneliness is overwhelming.",
    feeling: null,
    coped: null,
  },
  {
    id: "s04",
    lat: -23.5,
    lng: -46.6,
    lang: "en",
    text: "Depression took everything from me. I can barely get out of bed.",
    feeling: null,
    coped: "One thing a day. Just one. Yesterday I cooked dinner.",
  },
  {
    id: "s05",
    lat: 35.7,
    lng: 139.7,
    lang: "en",
    text: "Working 14-hour days and still can't afford rent.",
    feeling: null,
    coped: "Started journaling at night. Getting thoughts out of my head.",
  },
  {
    id: "s06",
    lat: 48.9,
    lng: 2.3,
    lang: "en",
    text: "Divorced. Kids live with their mom. The apartment feels empty.",
    feeling: null,
    coped: null,
  },
  {
    id: "s07",
    lat: 19.1,
    lng: 72.9,
    lang: "en",
    text: "My parents don't accept who I am. I have to pretend every day.",
    feeling: null,
    coped: "Found an online support group. They understand.",
  },
  {
    id: "s08",
    lat: -33.9,
    lng: 18.4,
    lang: "en",
    text: "Chronic pain nobody can see. Doctors say it's in my head.",
    feeling: null,
    coped: "Meditation app. 10 minutes. Doesn't fix it, but makes it bearable.",
  },
  {
    id: "s09",
    lat: 52.5,
    lng: 13.4,
    lang: "en",
    text: "Refugee. New language, new rules, old trauma.",
    feeling: null,
    coped: null,
  },
  {
    id: "s10",
    lat: 59.9,
    lng: 30.3,
    lang: "ru",
    text: "Не разговаривал ни с кем 3 недели. Забыл, как звучит мой голос.",
    feeling: null,
    coped: "Разговариваю с кошкой. Звучит глупо, но она слушает.",
  },
  {
    id: "s11",
    lat: 34.1,
    lng: -118.2,
    lang: "en",
    text: "Addicted. Clean for 47 days. Every day is a battle.",
    feeling: null,
    coped: "AA meetings every day. The people there saved my life.",
  },
  {
    id: "s12",
    lat: 1.3,
    lng: 103.8,
    lang: "en",
    text: "Everyone sees my success. Nobody sees my panic attacks at 3am.",
    feeling: null,
    coped: "Finally told one friend. Just one. It changed everything.",
  },
];
